// pages/HowItWorks.tsx

import Navbar from "@/app/components/Navbar"; // Adjust the path as necessary
import Footer from "@/app/components/Footer"; // Adjust the path as necessary
import Link from "next/link";
if (typeof window !== 'undefined') {
    // This code runs only in the browser
    console.log("This runs in the client");
}

export default function HowItWorks() {
    return (
        <div className="min-h-screen bg-gradient-to-b from-gray-100 to-gray-200">

            <main className="container mx-auto px-4 py-8">
                <h1 className="text-4xl font-bold text-center mb-4 text-gray-800">Creator of the Projects and Goals for the Project</h1>
                <p className="text-xl text-gray-600 max-w-2xl mx-auto text-justify mb-8">
             

                    This project aims to develop an application designed to detect videos generated by artificial intelligence (AI). The ultimate objective of the project is to enhance AI detection capabilities for images and to analyze videos frame by frame to establish an average AI detection rate. Since videos generated by AI consist of frames produced by AI algorithms, the project seeks to employ this understanding. Although this method may not be entirely reliable, future enhancements are envisioned through the utilization of machine learning and advanced AI techniques.
                    <br /><br /> 
                    The necessity of this project is based on the current developments in AI-generated content getting more popular every day. These include face recognition with applications such as facial recognition for security purposes, the emergence of virtual YouTubers (vtuber), and the proliferation of deep-fake videos. Despite the existence of tools capable of recognizing deepfake videos, there is currently no application tailored for the detection of non-deepfake videos. Moreover, it is foreseeable that advancements in AI technology will lead to exponential improvements in both AI-generated content and video manipulation techniques. Consequently, this improvement will cause us to not be able to separate truth and a lie digitally.  Addressing this issue constitutes the primary focus of the project.
                    <br /><br />
                    This project was created by Batur Alp Akyüz when
                    he was a 22-year-old student in Istanbul, Türkiye (Turkey),
                    as a design application project for a bachelor's degree in Mathematical Engineering
                    at Yildiz Technical University in early 2024.


                </p>
                <div className="text-center">
                    <Link href="/" className="text-blue-500 underline">
                        Go Back to Home
                    </Link>
                </div>
            </main>

        </div>
    );
}
